# Import

In [1]:
import pandas as pd
import os
import re
import emoji


import warnings
warnings.filterwarnings('ignore')

# txt to csv

In [2]:
df = pd.read_csv("../data/chat_ju.txt", delimiter='\t', encoding='utf-8')
df

      [11/1/21, 21:10:17] Ju: ‚ÄéLos mensajes y las llamadas est√°n cifrados de extremo a extremo. Nadie fuera de este chat, ni siquiera WhatsApp, puede leerlos ni escucharlos.
0                 ‚Äé[11/1/21, 21:10:17] üê•: ‚Äéaudio omitido
1                 ‚Äé[12/1/21, 13:14:04] üê•: ‚Äéaudio omitido
2                ‚Äé[12/1/21, 13:37:42] Ju: ‚Äéaudio omitido
3      [12/1/21, 14:22:35] üê•: Que guai amooooor la of...
4      [12/1/21, 14:22:50] üê•: Oiiii donali besis a la...
...                                                  ...
18066  [28/4/23, 15:09:53] üê•: tinc encara 10 min sino...
18067                  [28/4/23, 15:09:55] üê•: com vlguis
18068        [28/4/23, 15:10:00] üê•: uina h vas casa leni
18069  [28/4/23, 15:11:25] Ju: despres millor doncs amor
18070                     [28/4/23, 15:14:08] üê•: perfeüñ§üåª

[18071 rows x 1 columns]

In [3]:
#df = df.to_csv("../data/chat_ju.csv", index=False)

In [4]:
df = pd.read_csv("../data/chat_ju.csv")

# transform

## Setting columns

In [5]:
df.columns = ["col"]

#df.iloc[23]["col"].split(",")[0].replace("[","") 
df["Date"] = df["col"].str.split(",").str[0].str.replace("[", "")

#df.iloc[23]["col"].split(",")[1].split("]")[0].strip()
df["Time"] = df["col"].str.split(",").str[1].str.split("]").str[0].str.strip()

#df.iloc[22]["col"].split(":")[2].split("]")[1].strip()
df["Name"] = df["col"].str.split(":").str[2].str.split("]").str[1].str.strip()
df['Name'] = df['Name'].str.replace('üê•', 'Bego')

# df.iloc[0]["col"].split(":")[3].strip()
df["Message"] = df["col"].str.split(":").str[3].str.strip()

df.drop(columns=["col"], axis=1, inplace=True)

df

           Date      Time  Name                             Message
0      ‚Äé11/1/21  21:10:17  Bego                      ‚Äéaudio omitido
1      ‚Äé12/1/21  13:14:04  Bego                      ‚Äéaudio omitido
2      ‚Äé12/1/21  13:37:42    Ju                      ‚Äéaudio omitido
3       12/1/21  14:22:35  Bego        Que guai amooooor la ofi no?
4       12/1/21  14:22:50  Bego  Oiiii donali besis a la cami amore
...         ...       ...   ...                                 ...
18066   28/4/23  15:09:53  Bego       tinc encara 10 min sino dpres
18067   28/4/23  15:09:55  Bego                          com vlguis
18068   28/4/23  15:10:00  Bego                uina h vas casa leni
18069   28/4/23  15:11:25    Ju           despres millor doncs amor
18070   28/4/23  15:14:08  Bego                             perfeüñ§üåª

[18071 rows x 4 columns]

In [6]:
#df.head(10)

In [7]:
df.iloc[13839]["Message"]

'üòπüòπ‚ù§Ô∏è‚ù§Ô∏èüòπ‚ù§Ô∏è'

In [8]:
df.dropna(subset=['Message'], inplace=True)

In [9]:
df = df[~df['Message'].str.contains('\u200eaudio omitido')]
df

          Date      Time  Name                               Message
3      12/1/21  14:22:35  Bego          Que guai amooooor la ofi no?
4      12/1/21  14:22:50  Bego    Oiiii donali besis a la cami amore
5      12/1/21  14:23:33  Bego                        (I un per tuüå∏)
6      12/1/21  14:24:14  Bego            Vale parlem x dma cari√±ito
8      12/1/21  14:24:29  Bego  Que acabis d pssar un bon dia boniti
...        ...       ...   ...                                   ...
18066  28/4/23  15:09:53  Bego         tinc encara 10 min sino dpres
18067  28/4/23  15:09:55  Bego                            com vlguis
18068  28/4/23  15:10:00  Bego                  uina h vas casa leni
18069  28/4/23  15:11:25    Ju             despres millor doncs amor
18070  28/4/23  15:14:08  Bego                               perfeüñ§üåª

[17364 rows x 4 columns]

## Get Emojis

In [10]:
emoji_pattern = re.compile("["
    u"\U0001F600-\U0001F64F"  # emoticons
    u"\U0001F300-\U0001F5FF"  # symbols & pictographs
    u"\U0001F680-\U0001F6FF"  # transport & map symbols
    u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
    u"\U0001F900-\U0001F9FF"  # supplemental symbols and pictographs
    u"\U0001F1F2-\U0001F1F4"  # country flags
    u"\U0001F1E6-\U0001F1FF"  # regional indicator symbols
    u"\U0001F600-\U0001F64F"  # emoticons
    u"\U00002702-\U000027B0"  # dingbats
    u"\U000024C2-\U0001F251" 
    "]+", flags=re.UNICODE)

In [11]:
df['Emojis'] = df['Message'].str.findall(emoji_pattern)

In [12]:
df = df[df['Emojis'].apply(lambda x: len(x) > 0)]
df

,Date,Time,Name,Message,Emojis
5,12/1/21,14:23:33,Bego,(I un per tuüå∏),[üå∏]
14,14/1/21,10:09:55,Bego,‚òÄÔ∏è‚òÄÔ∏è‚òÄÔ∏è‚òÄÔ∏è‚òÄÔ∏è‚òÄÔ∏è‚ù§Ô∏è,[‚òÄÔ∏è‚òÄÔ∏è‚òÄÔ∏è‚òÄÔ∏è‚òÄÔ∏è‚òÄÔ∏è‚ù§Ô∏è]
15,14/1/21,11:04:39,Ju,Bdia bebita precioseta üíìüíìüíìüíï,[üíìüíìüíìüíï]
20,14/1/21,15:03:07,Bego,aiiiiii m'aniria tan be.. avui he fet compreta...,[üòà]
44,14/1/21,17:54:05,Ju,Perfect teqqqqüíì,[üíì]
...,...,...,...,...,...
18001,26/4/23,21:36:06,Ju,pica algo i quan surti d fontana taviso i et p...,[‚ú®]
18023,26/4/23,23:28:53,Ju,marxaree amor ‚ù§Ô∏è‚ù§Ô∏è,[‚ù§Ô∏è‚ù§Ô∏è]
18048,27/4/23,14:21:38,Ju,‚ù§Ô∏è,[‚ù§Ô∏è]
18058,28/4/23,12:26:34,Bego,et truco llavors???‚ù§Ô∏è,[‚ù§Ô∏è]
18070,28/4/23,15:14:08,Bego,perfeüñ§üåª,[üñ§üåª]

In [13]:
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

In [28]:
df['Time'] = pd.to_datetime(df['Time'], format='%H:%M:%S', errors='coerce')
df['Time'] = df['Time'].dt.time
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day
df['Year'] = df['Date'].dt.year

In [29]:
df

,Date,Time,Day,Hour,Name,Message,Emojis,Month,Year
5,2021-12-01,14:23:33,1,14,Bego,(I un per tuüå∏),[üå∏],12,2021
14,2021-01-14,10:09:55,14,10,Bego,‚òÄÔ∏è‚òÄÔ∏è‚òÄÔ∏è‚òÄÔ∏è‚òÄÔ∏è‚òÄÔ∏è‚ù§Ô∏è,[‚òÄÔ∏è‚òÄÔ∏è‚òÄÔ∏è‚òÄÔ∏è‚òÄÔ∏è‚òÄÔ∏è‚ù§Ô∏è],1,2021
15,2021-01-14,11:04:39,14,11,Ju,Bdia bebita precioseta üíìüíìüíìüíï,[üíìüíìüíìüíï],1,2021
20,2021-01-14,15:03:07,14,15,Bego,aiiiiii m'aniria tan be.. avui he fet compreta...,[üòà],1,2021
44,2021-01-14,17:54:05,14,17,Ju,Perfect teqqqqüíì,[üíì],1,2021
...,...,...,...,...,...,...,...,...,...
18001,2023-04-26,21:36:06,26,21,Ju,pica algo i quan surti d fontana taviso i et p...,[‚ú®],4,2023
18023,2023-04-26,23:28:53,26,23,Ju,marxaree amor ‚ù§Ô∏è‚ù§Ô∏è,[‚ù§Ô∏è‚ù§Ô∏è],4,2023
18048,2023-04-27,14:21:38,27,14,Ju,‚ù§Ô∏è,[‚ù§Ô∏è],4,2023
18058,2023-04-28,12:26:34,28,12,Bego,et truco llavors???‚ù§Ô∏è,[‚ù§Ô∏è],4,2023
18070,2023-04-28,15:14:08,28,15,Bego,perfeüñ§üåª,[üñ§üåª],4,2023

In [30]:
df['Hour'] = df['Time'].apply(lambda x: x.hour)
df

,Date,Time,Day,Hour,Name,Message,Emojis,Month,Year
5,2021-12-01,14:23:33,1,14,Bego,(I un per tuüå∏),[üå∏],12,2021
14,2021-01-14,10:09:55,14,10,Bego,‚òÄÔ∏è‚òÄÔ∏è‚òÄÔ∏è‚òÄÔ∏è‚òÄÔ∏è‚òÄÔ∏è‚ù§Ô∏è,[‚òÄÔ∏è‚òÄÔ∏è‚òÄÔ∏è‚òÄÔ∏è‚òÄÔ∏è‚òÄÔ∏è‚ù§Ô∏è],1,2021
15,2021-01-14,11:04:39,14,11,Ju,Bdia bebita precioseta üíìüíìüíìüíï,[üíìüíìüíìüíï],1,2021
20,2021-01-14,15:03:07,14,15,Bego,aiiiiii m'aniria tan be.. avui he fet compreta...,[üòà],1,2021
44,2021-01-14,17:54:05,14,17,Ju,Perfect teqqqqüíì,[üíì],1,2021
...,...,...,...,...,...,...,...,...,...
18001,2023-04-26,21:36:06,26,21,Ju,pica algo i quan surti d fontana taviso i et p...,[‚ú®],4,2023
18023,2023-04-26,23:28:53,26,23,Ju,marxaree amor ‚ù§Ô∏è‚ù§Ô∏è,[‚ù§Ô∏è‚ù§Ô∏è],4,2023
18048,2023-04-27,14:21:38,27,14,Ju,‚ù§Ô∏è,[‚ù§Ô∏è],4,2023
18058,2023-04-28,12:26:34,28,12,Bego,et truco llavors???‚ù§Ô∏è,[‚ù§Ô∏è],4,2023
18070,2023-04-28,15:14:08,28,15,Bego,perfeüñ§üåª,[üñ§üåª],4,2023

In [31]:
sort_cols = ['Date', 'Time', 'Day', 'Month', 'Year', 'Hour', 'Name', 'Message', 'Emojis']
df = df.reindex(columns=sort_cols)
df

,Date,Time,Day,Month,Year,Hour,Name,Message,Emojis
5,2021-12-01,14:23:33,1,12,2021,14,Bego,(I un per tuüå∏),[üå∏]
14,2021-01-14,10:09:55,14,1,2021,10,Bego,‚òÄÔ∏è‚òÄÔ∏è‚òÄÔ∏è‚òÄÔ∏è‚òÄÔ∏è‚òÄÔ∏è‚ù§Ô∏è,[‚òÄÔ∏è‚òÄÔ∏è‚òÄÔ∏è‚òÄÔ∏è‚òÄÔ∏è‚òÄÔ∏è‚ù§Ô∏è]
15,2021-01-14,11:04:39,14,1,2021,11,Ju,Bdia bebita precioseta üíìüíìüíìüíï,[üíìüíìüíìüíï]
20,2021-01-14,15:03:07,14,1,2021,15,Bego,aiiiiii m'aniria tan be.. avui he fet compreta...,[üòà]
44,2021-01-14,17:54:05,14,1,2021,17,Ju,Perfect teqqqqüíì,[üíì]
...,...,...,...,...,...,...,...,...,...
18001,2023-04-26,21:36:06,26,4,2023,21,Ju,pica algo i quan surti d fontana taviso i et p...,[‚ú®]
18023,2023-04-26,23:28:53,26,4,2023,23,Ju,marxaree amor ‚ù§Ô∏è‚ù§Ô∏è,[‚ù§Ô∏è‚ù§Ô∏è]
18048,2023-04-27,14:21:38,27,4,2023,14,Ju,‚ù§Ô∏è,[‚ù§Ô∏è]
18058,2023-04-28,12:26:34,28,4,2023,12,Bego,et truco llavors???‚ù§Ô∏è,[‚ù§Ô∏è]
18070,2023-04-28,15:14:08,28,4,2023,15,Bego,perfeüñ§üåª,[üñ§üåª]

In [16]:
df.groupby("Name").agg("count")

      Date  Time  Message  Emojis
Name
Bego   442   442      442     442
Ju     861   861      861     861

In [17]:
pd.DataFrame(df.groupby(["Name", "Date"])["Name"].count())

## Setting columns

                 Name
Name Date
Bego 2021-01-07     1
     2021-01-11     1
     2021-01-12     4
     2021-01-14     2
     2021-01-15     3
...               ...
Ju   2023-10-01     3
     2023-10-04     1
     2023-11-01     2
     2023-12-02     1
     2023-12-04     3

[648 rows x 1 columns]